--CHAP10 DML
-- 10-1 
CREATE TABLE DEPT_TEMP 
    AS SELECT * FROM DEPT;

-- 10-2
SELECT * FROM DEPT_TEMP;

--1분 복습 EMP_TEMP10
CREATE TABLE EMP_TEMP10
     AS SELECT * FROM EMP;
     
SELECT * FROM EMP_TEMP10;

-- 10-3 데이터 추가하기
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
             VALUES (50, 'DATABASE', 'SEOUL');
SELECT * FROM DEPT_TEMP;
COMMIT;

-- INSERT 오류
--입력값의 갯수 주의
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
           VALUES(60, 'NETWORK'); -- NOT ENOUGH VALUES

INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
           VALUES(60, 'NETWORK', 'BUSAN', 'WRONG'); -- TOO MANY VALUES

--입력값의 자료형 주의          
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
           VALUES('WRONG', 'NETWORK', 'BUSAN'); --ORA-01722: invalid number
           
-- 입력값의 사이즈
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
           VALUES(600, 'NETWORK', 'BUSAN'); 
-- ORA-01438: value larger than specified precision allowed for this column

--10-4 열지정 없이 데이터 추가하기
INSERT INTO DEPT_TEMP
       VALUES(60, 'NETWORK', 'BUSAN');
COMMIT;
SELECT *FROM DEPT_TEMP;

--10-5 NULL을 지정하여 입력하기
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
  VALUES(70, 'WEB', NULL);
COMMIT;
SELECT*FROM DEPT_TEMP;

INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
  VALUES(80, 'MOBILE', '');
SELECT * FROM DEPT_TEMP;
COMMIT;

--10-7 열을 명시하지 않고 INSERT문 작성
INSERT INTO DEPT_TEMP(DEPTNO, LOC)
        VALUES (90, 'INCHEON');
COMMIT;

-- 10-8
CREATE TABLE EMP_TEMP
    AS SELECT * FROM EMP WHERE 1 <> 1;
    
SELECT * FROM EMP_TEMP;

SELECT * FROM EMP WHERE 1=1
AND HIREDATE = '19810402'
AND ENAME = 'JONES';

--10-9 INSERT문으로 날짜 데이터 입력(날짜사이에 /)
INSERT INTO EMP_TEMP
(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (9999, '홍길동', 'PRESIDENT', NULL, '2001/01/01',5000,1000,10);
COMMIT;

SELECT * FROM EMP_TEMP;

INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (1111, '성춘향', 'MANAGER', 9999, '2001-01-05',4000,NULL,20);

-- 날짜 데이터 입력 시 유의점 
-- 년월일 반대로 일/월/년 -> 오류발생
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (2111, '이순신', 'MANAGER', 9999, '07/01/2001', 4000, NULL, 20);

-- 10-12 TO_DATE
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (2111, '이순신', 'MANAGER', 9999,
        TO_DATE('07/01/2001', 'DD/MM/YYYY'), 4000, NULL, 20);

SELECT SYSDATE FROM DUAL; 
--10-13
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (3111, '심청이','MANAGER', 9999, SYSDATE, 4000, NULL, 30);

SELECT EMPNO, ENAME, TO_CHAR(HIREDATE, 'YYYY/MM/DD HH24:MI:SS')
  FROM EMP_TEMP;
  COMMIT;
 SELECT * FROM EMP_TEMP;
 
 --서브쿼리로 여러 데이터 추가하기
 --10-14
 INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
      SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, E.DEPTNO
        FROM EMP E, SALGRADE S
       WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
         AND S.GRADE = 1;

SELECT * FROM EMP_TEMP;              

-- INSERT문에서 서브쿼리 사용할 때 주의할 점
-- VALUES절은 사용하지 않는다
-- 컬럼 수는 일치 해야한다.

--중간문제

SELECT COUNT(*) FROM COUNTRIES;  -- 25 -> 29
SELECT COUNT(*) FROM DEPARTMENTS;-- 27 -> 31

--1번
INSERT INTO COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID)
  VALUES ( 'AT', 'Austria', 1);
INSERT INTO COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID)  
  VALUES ( 'NO', 'Norway', 1);
INSERT INTO COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID)  
  VALUES ( 'ID', 'Indonesia', 3);
INSERT INTO COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID)  
  VALUES ( 'TR', 'Turkey', 4);
SELECT *FROM COUNTRIES
 WHERE COUNTRY_ID IN('AT','NO','ID','TR');
  
--2번    
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
  VALUES( 280, 'Advertising', 200, 1700);
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)  
  VALUES( 290, 'Sales Support', 145, 1700);
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)  
  VALUES( 300, 'Education', NULL, 1700);
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)  
  VALUES( 310, 'E-Commerce', NULL, 1700);
SELECT*FROM DEPARTMENTS
 WHERE DEPARTMENT_ID IN (280, 290, 300, 310);
 
 COMMIT;
 
 -- 10 -2절 테이블에 있는 데이터 수정하기
 CREATE TABLE DEPT_TEMP2
     AS SELECT * FROM DEPT;
     
SELECT * FROM DEPT_TEMP2;

-- 10-16
UPDATE DEPT_TEMP2
   SET LOC ='SEOUL';
 
ROLLBACK;   
SELECT * FROM DEPT_TEMP2;   

SELECT * FROM DEPT_TEMP2
 WHERE DEPTNO =40;
 
 UPDATE DEPT_TEMP2
    SET DNAME = 'DATABASE'
       , LOC = 'SEOUL'
   WHERE DEPTNO =40;
COMMIT;   

--1분 복습
SELECT*FROM EMP_TEMP
   WHERE SAL<=2500;

UPDATE EMP_TEMP
   SET COMM = 50
 WHERE SAL<=2500; 
 COMMIT;
 
-- 서브쿼리 사용 수정
--10-19
SELECT *
  FROM DEPT_TEMP2
 WHERE DEPTNO = 40;
-- 40 DATABASE SEOUL 

 SELECT DNAME, LOC
  FROM DEPT
 WHERE DEPTNO = 40;
-- 40 OPERAIONS BOSTON
UPDATE DEPT_TEMP2
  SET (DNAME, LOC) = (SELECT DNAME, LOC
                        FROM DEPT
                       WHERE DEPTNO = 40)
 WHERE DEPTNO = 40;
 
 SELECT * FROM DEPT_TEMP2;
-- 열 하나하나를 수정하는 경우
UPDATE DEPT_TEMP2
   SET DNAME = (SELECT DNAME FROM DEPT
                 WHERE DEPTNO = 40)
        , LOC = (SELECT LOC FROM DEPT
                  WHERE DEPTNO = 40)
  WHERE DEPTNO = 40;                
            
 -- UPDATE 문의 WHERE 절에 서브쿼리 사용가능
  SELECT * FROM DEPT_TEMP2
   WHERE DEPTNO=40;
   
   UPDATE DEPT_TEMP2
   SET LOC = 'SEOUL'
    WHERE DEPTNO = (SELECT DEPTNO
                      FROM DEPT_TEMP2
                     WHERE DNAME = 'OPERATIONS');
                     
SELECT * FROM JOBS
 WHERE JOB_ID IN('ADV', 'IT ENG', 'IT RES');

INSERT INTO JOBS 
VALUES ('ADV', 'Advisor', 10000, 20000);
INSERT INTO JOBS
VALUES ('IT ENG', 'Engineer', 8000, 15000);
INSERT INTO JOBS
VALUES ('IT RES', 'Researcher', 12000, 22000);
COMMIT;

--1번
SELECT * FROM DEPARTMENTS
 WHERE DEPARTMENT_ID IN ( 280, 290, 300, 310);
 
 UPDATE DEPARTMENTS
    SET LOCATION_ID = 2000 
  WHERE DEPARTMENT_ID IN ( 280, 290, 300, 310); 
  
 UPDATE DEPARTMENTS
    SET MANAGER_ID = 102
  WHERE DEPARTMENT_ID IN(300,310);

--2번  
SELECT * FROM JOBS
 WHERE JOB_ID IN( 'ADV', 'IT ENG', 'IT RES');

 UPDATE JOBS
   SET JOB_TITLE = 'Research Engineer'
      , MAX_SALARY = 24000
    WHERE JOB_ID IN( 'IT RES');

 UPDATE JOBS
   SET  MIN_SALARY = 12000
      , MAX_SALARY = 22000
    WHERE JOB_ID IN( 'ADV');    

 UPDATE JOBS
   SET MAX_SALARY = 16000
    WHERE JOB_ID IN('IT ENG');
COMMIT;    

CREATE TABLE EMP_TEMP2
    AS SELECT * FROM EMP;
    
SELECT * FROM EMP_TEMP2;

SELECT * FROM EMP_TEMP2
 WHERE JOB = 'MANAGER';
 
-- 10-23 
DELETE FROM  EMP_TEMP2
 WHERE JOB='MANAGER';

SELECT * FROM EMP_TEMP2;

SELECT E.EMPNO
  FROM EMP_TEMP2 E, SALGRADE S
 WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
   AND S.GRADE = 3
   AND E.DEPTNO = 30;
-- 7499
-- 7844
SELECT * 
  FROM EMP_TEMP2
 WHERE EMPNO IN (7499, 7844);
 
DELETE FROM EMP_TEMP2
 WHERE EMPNO IN(SELECT E.EMPNO
                  FROM EMP_TEMP2 E, SALGRADE S
                 WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
                   AND S.GRADE = 3
                   AND E.DEPTNO = 30);
 COMMIT;
 
SELECT COUNT(*) FROM EMP_TEMP2;  -- 9

-- 10-25
DELETE FROM EMP_TEMP2;
ROLLBACK;

DML -- INSERT, UPDATE, DELETE DQL: SELECT
DDL 

TRUNCATE TABLE EMP_TEMP2; -- 데이터만 삭제

--잊기 전에 한 번 더!
CREATE TABLE CHAP10HW_EMP1 
    AS SELECT * FROM EMP;
CREATE TABLE CHAP10HW_DEPT1 
    AS SELECT * FROM DEPT;
CREATE TABLE CHAP10HW_SALGRADE1 
    AS SELECT * FROM SALGRADE;
    
 --1번
 SELECT * FROM CHAP10HW_DEPT1;
 SELECT * FROM DEPT;
 
 INSERT INTO CHAP10HW_DEPT1(DEPTNO, DNAME, LOC)
 VALUES (50, 'ORACLE', 'BUSAN');
  INSERT INTO CHAP10HW_DEPT1(DEPTNO, DNAME, LOC)
 VALUES (60, 'SQL', 'ILSAN');
  INSERT INTO CHAP10HW_DEPT1(DEPTNO, DNAME, LOC)
 VALUES (70, 'SELECT', 'INCHEON');
  INSERT INTO CHAP10HW_DEPT1(DEPTNO, DNAME, LOC)
 VALUES (80, 'DML', 'BUNDANG');
 
--2번
SELECT * FROM CHAP10HW_EMP1;

INSERT INTO CHAP10HW_EMP1(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
  VALUES (7201,'TEST_USER1','MANAGER',7788,'20160102',4500,NULL,50);
INSERT INTO CHAP10HW_EMP1(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
  VALUES (7202,'TEST_USER2','CLERK',7201,'2016-02-21',1800,NULL,50);
INSERT INTO CHAP10HW_EMP1(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
  VALUES (7203,'TEST_USER3','ANALYST',7201,'2016/04/11',3400,NULL,60);
INSERT INTO CHAP10HW_EMP1(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
  VALUES (7204,'TEST_USER4','SALESMAN',7201,'2016-05-31',2700,300,60);
INSERT INTO CHAP10HW_EMP1(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
  VALUES (7205,'TEST_USER5','CLERK',7201,'2016-07-20',2600,NULL,70);
INSERT INTO CHAP10HW_EMP1(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
  VALUES (7206,'TEST_USER6','CLERK',7201,'2016/09/08',2600,NULL,70);
INSERT INTO CHAP10HW_EMP1(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
  VALUES (7207,'TEST_USER7','LECTURER',7201,'2016-10-28',2300,NULL,80);
INSERT INTO CHAP10HW_EMP1(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
  VALUES (7208,'TEST_USER8','STUDENT',7201,'2018-03-09',1200,NULL,80);  
  
COMMIT;  
--3번
SELECT* FROM CHAP10HW_EMP1
WHERE SAL > (SELECT AVG(SAL)
                FROM CHAP10HW_EMP1
                WHERE DEPTNO = 50);

UPDATE CHAP10HW_EMP1
  SET DEPTNO = 70
  WHERE SAL > (SELECT AVG(SAL)
                FROM CHAP10HW_EMP1
                WHERE DEPTNO = 50);
ROLLBACK;                
--4번

UPDATE CHAP10HW_EMP1
   SET SAL = SAL *1.1, DEPTNO=80
 WHERE HIREDATE > (SELECT HIREDATE
                     FROM CHAP10HW_EMP1
                    WHERE DEPTNO =60);
                    
--5번
DELETE FROM CHAP10HW_EMP1
 WHERE EMPNO IN ( SELECT EMPNO
                    FROM SALGRADE S, CHAP10HW_EMP1 E
                   WHERE E.SAL BETWEEN LOSAL AND HISAL
                     AND S.GRADE = 5);
                         
SELECT* FROM CHAP10HW_EMP1;
COMMIT;
                                 